# Generated by Django 5.2.3 on 2025-06-19 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usercategorylimit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategorylimit',
            name='limit_type',
            field=models.CharField(choices=[('day', 'День'), ('week', 'Неделя'), ('month', 'Месяц')], default='month', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usercategorylimit',
            unique_together={('user', 'category', 'limit_type')},
        ),
    ]
